cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='cart.index'),
    path('<int:id>/add/', views.add, name='cart.add'),
    path('clear/', views.clear, name='cart.clear'),
    path('purchase/', views.purchase, name='cart.purchase'),
]

moviesstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('petitions/', include('petitions.urls')),
]
urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

petitions/urls.py
from django.urls import path
from . import views

app_name = 'petitions'

urlpatterns = [
    path('', views.petition_list, name='list'),
    path('create/', views.create_petition, name='create'),
    path('vote/<int:pk>/', views.vote_petition, name='vote'),
]

moviesstore/templates/base.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <title>{{ template_data.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <!-- Header -->
     <nav class="p-3 navbar navbar-dark bg-dark
         navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand"
           href="{% url 'home.index' %}">
          <img src="{% static 'img/logo.png' %}" alt="logo"
               height="40" />
        </a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"
             id="navbarNavAltMarkup">
          <div class="navbar-nav ms-auto navbar-ml">
            <a class="nav-link"
               href="{% url 'home.about' %}">About</a>
            <a class="nav-link" 
                href="{% url 'movies.index' %}">Movies</a>
            <a class="nav-link"
              href="{% url 'cart.index' %}">Cart</a>
            <a class="nav-link"
              href="{% url 'petitions:list' %}">Petitions</a>
            <div class="vr bg-white mx-2 d-none
              d-lg-block"></div>
            {% if user.is_authenticated %}
            <a class="nav-link"
              href="{% url 'accounts.orders' %}">Orders
            </a>
            <a class="nav-link"
              href="{% url 'accounts.logout' %}">Logout ({{user.username }})</a>
            {% else %}
            <a class="nav-link" href="{% url 'accounts.login' %}">Login</a>
            <a class="nav-link" href="{% url 'accounts.signup' %}">Sign Up</a>
            {% endif %}
        </div>
        </div>
      </div>
    </nav>
    <!-- Header -->
    <div>
      {% block content %}
      {% endblock content %}
    </div>
    <!-- Footer -->
     <section class="p-3 ms-footer d-none d-md-block">
      <div class="container">
        <div class="row mt-3 text-white">
          <div class="col-md-6 col-lg-6 col-xl-6
               mx-auto mb-4">
            <b>MOVIES STORE</b>
            <hr />
            <p>
              Welcome to Movies Store, your premier online
              destination for a cinematic adventure like no
              other! Dive into the world of movies from the
              comfort of your own home with our user-
              friendly and immersive online movie store.
            </p>
          </div>
          <div class="col-md-3 col-lg-3 col-xl-3
               mx-auto mb-4">
            <b>LINKS</b>
            <hr />
            <p><a class="nav-link"
              href="{% url 'home.about' %}">
              About
            </a></p>
          </div>
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto
               mb-4">
            <b>CONTACT</b>
            <hr />
            <p><i class="fas fa-home me-2"></i>
              150-2345 Tokyo-to, Japan
            </p>
            <p><i class="fas fa-envelope me-2"></i>
              info@moviesstore.com
            </p>
            <p><i class="fas fa-phone me-2"></i>
              +81 03-3333-3333
            </p>
          </div>
        </div>
      </div>
    </section>
    <section class="p-3 ms-footer-bottom bg-dark">
      <div class="container d-flex
           justify-content-between">
        <div class="me-5 text-white">
          <span>DESIGNED BY
            <a href="https://www.x.com/danielgarax"
            target="_blank">DANIEL CORREA</a> &
            <a href="https://www.x.com/greglim81"
            target="_blank">GREG LIM</a>
          </span>
        </div>
        <div class="text-white">
          <span>© Copyright - 2024</span>
        </div>
      </div>
    </section>
    <!-- Footer -->
  </body>
</html>